services:
  web:
    build:   
      context: app
      dockerfile: Dockerfile
      target: builder  
    hostname: djngocon  
    container_name: djngoc
    image: djngoimg:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:rw
      - app_data:/app:rw
    networks:
      - djngo_net

volumes:
  app_data:
    name : djv
    driver: local

networks:
  djngo_net:
    name : djv
    driver: bridge

